# Generated by Django 2.0.1 on 2018-05-02 10:10
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_auto_20180210_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabExtSchedule',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('second', models.CharField(
                    default='*', max_length=64, verbose_name='second')),
                ('minute', models.CharField(
                    default='*', max_length=64, verbose_name='minute')),
                ('hour', models.CharField(
                    default='*', max_length=96, verbose_name='hour')),
                ('day_of_week', models.CharField(
                    default='*', max_length=64, verbose_name='day of week')),
                ('day_of_month', models.CharField(
                    default='*', max_length=124, verbose_name='day of month')),
                ('month_of_year', models.CharField(
                    default='*', max_length=240, verbose_name='month of year')),
            ],
            options={
                'ordering': [
                    'month_of_year', 'day_of_month',
                    'day_of_week', 'hour', 'minute', 'second',
                ],
                'verbose_name': 'crontabext',
                'verbose_name_plural': 'crontabexts',
            },
        ),
        migrations.AddField(
            model_name='periodictask',
            name='crontabext',
            field=models.ForeignKey(
                blank=True, help_text='Use one of interval/crontabext',
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='django_celery_beat.CrontabExtSchedule',
                verbose_name='crontabext')
        )
    ]
